# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
            ],
            options={
                'verbose_name': 'Голос за книгу',
                'verbose_name_plural': 'Голоса за книгу',
                'db_table': 'user_book_vote',
            },
        ),
        migrations.CreateModel(
            name='VoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Доступна ли для голосования')),
                ('goal', models.IntegerField(blank=100, default=100, verbose_name='Цель')),
                ('fund_interval', models.IntegerField(default=100, verbose_name='Время на сбор(в днях)')),
                ('fund_need', models.IntegerField(default=1000, verbose_name='Необходимая сумма')),
                ('is_fund_sent', models.BooleanField(default=False, verbose_name='Ушла на франдрайз')),
            ],
            options={
                'verbose_name': 'Книга на голосование',
                'verbose_name_plural': 'Книги на голосование',
                'db_table': 'vote_book',
            },
        ),
    ]
