# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('book_vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votebook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.user', verbose_name='Кто добавил'),
        ),
        migrations.AddField(
            model_name='userbookvote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_vote.votebook', verbose_name='Книга за которую проголосовал'),
        ),
        migrations.AddField(
            model_name='userbookvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.user', verbose_name='Чей голос'),
        ),
    ]
