# Generated by Django 4.1.1 on 2022-10-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_vote', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votebook',
            name='goal',
        ),
        migrations.AddField(
            model_name='votebook',
            name='description',
            field=models.TextField(default='Описание книги', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='votebook',
            name='link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ссылка на книгу'),
        ),
        migrations.AddField(
            model_name='votebook',
            name='price_after_done',
            field=models.IntegerField(default=0, verbose_name='Цена после сбора'),
        ),
        migrations.AddField(
            model_name='votebook',
            name='price_common',
            field=models.IntegerField(default=0, verbose_name='Цена для не подписчика'),
        ),
        migrations.AddField(
            model_name='votebook',
            name='price_for_sub',
            field=models.IntegerField(default=0, verbose_name='Цена для подписчика'),
        ),
        migrations.AddField(
            model_name='votebook',
            name='vote_goal',
            field=models.IntegerField(blank=100, default=100, verbose_name='Необходимое кол-во голосов'),
        ),
    ]
