# Generated by Django 4.1.1 on 2022-10-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='sub_price_id',
            new_name='sub_price',
        ),
    ]
