# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('book_archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedarchivebook',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.user'),
        ),
        migrations.AddField(
            model_name='bookarchive',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_archive.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='bookarchive',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_archive.genre', verbose_name='Жанр'),
        ),
    ]
