# Generated by Django 4.1.1 on 2022-10-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_archive', '0003_remove_bookarchive_buy_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookarchive',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_archive.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookarchive',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bookarchive',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Год'),
        ),
    ]
