# Generated by Django 4.1.1 on 2022-10-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_archive', '0004_alter_bookarchive_author_alter_bookarchive_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedarchivebook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='purchasedarchivebook',
            old_name='user_id',
            new_name='user',
        ),
    ]
