# Generated by Django 4.1.1 on 2022-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_archive', '0006_genre_number_alter_bookarchive_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(blank=True, default='1', max_length=128, null=True, verbose_name='Наименование'),
        ),
    ]
