# Generated by Django 4.1.1 on 2022-11-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_archive', '0007_alter_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=256, verbose_name='ФИО'),
        ),
    ]
