# Generated by Django 4.1.1 on 2022-10-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_postvote_post_post_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vote',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.postvote', verbose_name='Голосование к посту'),
        ),
    ]
