# Generated by Django 4.1.1 on 2022-10-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvoteoptions',
            name='post_vote',
        ),
        migrations.AddField(
            model_name='postvote',
            name='post_option',
            field=models.ManyToManyField(to='post.postvoteoptions'),
        ),
    ]
