# Generated by Django 4.1.1 on 2022-10-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_postvoteoptions_post_vote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(blank=True, default=None, null=True, verbose_name='Вариант опроса')),
                ('collected_votes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Проголосовало за этот вариант')),
            ],
            options={
                'verbose_name': 'Вариант голосования',
                'verbose_name_plural': 'Посты - голосования варианты',
                'db_table': 'vote_choice',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='post_option',
        ),
        migrations.AddField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='postvote',
            name='title',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Название опроса'),
        ),
        migrations.DeleteModel(
            name='PostVoteOptions',
        ),
        migrations.AddField(
            model_name='votechoice',
            name='post_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postvote'),
        ),
    ]
