# Generated by Django 4.1.1 on 2022-10-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_votechoice_remove_post_vote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postvote',
            options={'verbose_name': 'Опрос в посте', 'verbose_name_plural': 'Опросы в посте'},
        ),
        migrations.AlterModelOptions(
            name='votechoice',
            options={'verbose_name': 'Вариант ответа в опросе', 'verbose_name_plural': 'Варианты ответов в вопросе'},
        ),
        migrations.AlterField(
            model_name='postvote',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название опроса'),
        ),
        migrations.AlterField(
            model_name='votechoice',
            name='choice_text',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Вариант опроса'),
        ),
    ]
