# Generated by Django 4.1.1 on 2022-10-26 05:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_remove_settings_book_request_title_limit_and_more'),
        ('post', '0006_alter_postvote_options_alter_votechoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votechoice',
            name='collected_votes',
        ),
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.CharField(max_length=128)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.user')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postvote')),
            ],
        ),
    ]
