# Generated by Django 4.1.1 on 2022-10-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_votechoice_collected_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votechoice',
            name='collected_votes',
        ),
    ]
