# Generated by Django 4.1.1 on 2022-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_votechoice_collected_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Ссылка в кнопке'),
        ),
    ]
