# Generated by Django 4.1.1 on 2022-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='votechoice',
            name='collected_votes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Проголосовало за этот вариант'),
        ),
    ]
