# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribe', '0001_initial'),
        ('book', '0002_initial'),
        ('book_archive', '0002_initial'),
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Статус оплаты',
                'verbose_name_plural': 'Статусы оплаты',
                'db_table': 'payment_status',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='Тип')),
                ('top_up', models.IntegerField(blank=True, null=True, verbose_name='Сумма пополнения')),
                ('payment_method', models.CharField(blank=True, max_length=128, null=True, verbose_name='Способ оплаты')),
                ('book_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_archive.bookarchive')),
                ('book_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Книга из фандрайзинга')),
                ('subscribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.subprice', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'db_table': 'operation',
            },
        ),
    ]
