# Generated by Django 4.1.1 on 2022-10-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='payment_method',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='book_archive',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='book_fund',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='subscribe',
        ),
    ]
