# Generated by Django 4.1.1 on 2022-10-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_payment_method_operation_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='payload',
            field=models.CharField(blank=True, max_length=128, verbose_name='Payload'),
        ),
    ]
