# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('all_subs_counter', models.IntegerField(default=0, verbose_name='Общее количество купивших подписку')),
                ('no_buy_users_counter', models.IntegerField(default=0, verbose_name='Количество пользователей не купивших подписку')),
                ('block_users_counter', models.IntegerField(default=0, verbose_name='Количество пользователей заблокировавших бота')),
                ('archive_books_sum', models.IntegerField(default=0, verbose_name='Сумма покупок книг из архива')),
                ('archive_books_count', models.IntegerField(default=0, verbose_name='Количество купленных книг из архива')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'db_table': 'statistic',
            },
        ),
    ]
