# Generated by Django 4.1.1 on 2022-10-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='all_subs_counter',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='no_buy_users_counter',
        ),
    ]
