# Generated by Django 4.1.1 on 2022-10-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_remove_statistic_all_subs_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='archive_books_count',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='archive_books_sum',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='block_users_counter',
        ),
    ]
