# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(blank=True, default='en', max_length=2, verbose_name='Код языка')),
                ('name', models.CharField(max_length=64, verbose_name='Название языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата вопроса')),
                ('text', models.TextField(verbose_name='Текст')),
                ('answer', models.TextField(default=None, null=True, verbose_name='Ответ')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечен ли')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('link', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка')),
                ('register_count', models.IntegerField(default=0, verbose_name='Кол-во регистраций')),
            ],
            options={
                'verbose_name': 'Реферальный код',
                'verbose_name_plural': 'Реферальные коды',
                'db_table': 'referral',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('question_symbols_limit', models.IntegerField(default=300, verbose_name='Лимит символов в вопросе (0 для отключения)')),
                ('register_menu', models.TextField(verbose_name='Меню выбора языка при регистрации')),
                ('top_up_limit', models.IntegerField(default=10000, verbose_name='Лимит пополнения баланса')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='ID пользователя в Telegram')),
                ('username', models.CharField(max_length=128, verbose_name='Имя пользователя')),
                ('mention', models.CharField(max_length=128, verbose_name='Обращение')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('is_block', models.BooleanField(default=False, verbose_name='Заблокировал ли бота')),
                ('show_progress', models.BooleanField(default=False, verbose_name='Показывать ли прогресс сбора')),
                ('deposit', models.IntegerField(default=0, verbose_name='Депозит')),
                ('subscribe_time', models.IntegerField(default=0, verbose_name='Месяцы подписки')),
                ('payment_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Сохраненный способ оплаты')),
                ('is_auto_pay', models.BooleanField(default=True, verbose_name='Автоплатеж')),
                ('not_end_payment', models.BooleanField(default=False, verbose_name='Не закончил оплату')),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='config.language', verbose_name='Язык')),
                ('referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.referral', verbose_name='Реферал')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
    ]
