# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribe', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscribe.subscribestatus'),
        ),
        migrations.AddField(
            model_name='question',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.user', verbose_name='От пользователя'),
        ),
    ]
