# Generated by Django 4.1.1 on 2022-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='register_menu',
        ),
        migrations.AddField(
            model_name='settings',
            name='book_request_title_limit',
            field=models.IntegerField(default=256, verbose_name='Лимит для названия предложенной книги'),
        ),
    ]
