# Generated by Django 4.1.1 on 2022-10-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remove_settings_register_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='book_request_title_limit',
        ),
        migrations.AddField(
            model_name='settings',
            name='author_limit',
            field=models.IntegerField(default=128, verbose_name='Лимит для автора'),
        ),
        migrations.AddField(
            model_name='settings',
            name='book_title_limit',
            field=models.IntegerField(default=128, verbose_name='Лимит для названия предложенной книги'),
        ),
        migrations.AddField(
            model_name='settings',
            name='promo_code_limit',
            field=models.IntegerField(default=64, verbose_name='Лимит длины промокода'),
        ),
    ]
