# Generated by Django 4.1.1 on 2022-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='genre',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Жанр'),
        ),
    ]
