# Generated by Django 4.1.1 on 2022-10-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_archive', '0003_remove_bookarchive_buy_count'),
        ('book_request', '0003_bookrequest_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_archive.genre', verbose_name='Жанры'),
        ),
    ]
