# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала сбора')),
                ('end_date', models.DateField(verbose_name='Дата конца сбора')),
                ('goal_sum', models.IntegerField(verbose_name='Необходимая сумма')),
                ('collected_sum', models.IntegerField(default=0, verbose_name='Собранная сумма')),
                ('link', models.CharField(max_length=256, verbose_name='Ссылка на книгу')),
                ('is_done', models.BooleanField(default=False, verbose_name='Собрано ли')),
                ('price_after_done', models.IntegerField(verbose_name='Цена после сбора')),
                ('price_for_sub', models.IntegerField(verbose_name='Цена для подписчика')),
                ('price_common', models.IntegerField(verbose_name='Цена для не подписчика')),
                ('is_available', models.BooleanField(blank=True, default=False, verbose_name='Доступна ли для скачивания')),
                ('is_notification_sent', models.BooleanField(blank=True, default=False, verbose_name='Отправлено ли уведомление')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'book',
            },
        ),
    ]
