# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(blank=True, to='config.user', verbose_name='Заплатившие пользователи'),
        ),
    ]
