# Generated by Django 4.1.1 on 2022-10-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribe', '0001_initial'),
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mode', models.CharField(choices=[('O', 'Одноразовый'), ('M', 'Многоразовый')], default='O', max_length=1, verbose_name='Одно/многоразовый')),
                ('user_mode', models.CharField(choices=[('O', 'Однопользовательский'), ('M', 'Многопользовательский')], default='O', max_length=1, verbose_name='Одно/многопользовательский')),
                ('promo_code', models.CharField(max_length=64, unique=True, verbose_name='Промокод')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован ли')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен ли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sub_price_id', models.ManyToManyField(to='subscribe.subprice', verbose_name='На какие подписки')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_code',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(choices=[('1', 'Активен'), ('0', 'Не активен')], default='1', max_length=1, verbose_name='Активен')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo_code.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.user')),
            ],
            options={
                'verbose_name': 'Пользователь промокода',
                'verbose_name_plural': 'Пользователи промокода',
                'db_table': 'promo_code_user',
            },
        ),
    ]
