# Generated by Django 4.1.1 on 2022-10-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_code', '0002_remove_promocode_is_active_remove_promocode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='Промокод'),
        ),
    ]
